### ISSUE TITLE
[FR] Ability to disable system accent

### ISSUE THREAD

**Issue by Omegaplexx** [F0x1d/LogFox#138]
EN: Hello. In Android 12, there is an option to use Material You system color accent for all apps. Many of them support disabling this option. Could you please add it? Thanks

RU: Здравствуйте. В Android 12 появилась возможность использовать системный цветовой акцент Material You для всех приложений. Многие из них поддерживают отключение этой опции. Не могли бы вы, пожалуйста, добавить её? Спасибо

**Comment by F0x1d** [comment]
Why would you disable it? Isn't it beautiful?

**Comment by Omegaplexx** [comment]
I prefer the apps own color instead of the system's dull green based on my beautiful forest wallpaper. Shouldn't the fox that read the logs be red? :)

**Comment by drogga** [comment]
It's orange (not red) and I suggested the dev. (in other place) to add a custom accent colors picker, being some pre-build or using a color picker with a hex value option (there is a code here on GH already that can be used/injected, probably not much effort is needed), because on pre-12 I can't change it from anywhere.
_(there are more things that need improvements and implementation, so this is kind of low priority)_

**Comment by Omegaplexx** [comment]
> It's orange (not red)

I meant red as deep orange shade of red. Both Russian words "Рыжий" (color of the fox) and "Красный" (strawberry color) are Red in the English.

> I suggested the dev. (in other place) to add a custom accent colors picker

Good idea, but I don't think the developer will devote much time to the design. A simple function to disable the use of Monet colors should be enough.

**Comment by F0x1d** [comment]
done in v2.0.2
