### ISSUE TITLE
[F] Indication that some filter has applied

### ISSUE THREAD

**Issue by mizzunet** [F0x1d/LogFox#72]
Some kind of indication when filter is applied will be great, I think.
 Once, I opened LogFox the list was empty and I assumed it could be root permission. So, I tried,
denying/grant su access, "Restart service", force stop. Until I figured out it had a filter that I had added last time I used.

Thanks :)

**Comment by F0x1d** [comment]
Any suggestions where/how LogFox should indicate it?

**Comment by Jesse205** [comment]
![Screenshot_20231118_110954_com.maltaisn.notes.sync.jpg](https://github.com/F0x1d/LogFox/assets/51242302/cc98fc32-c2ea-446f-b2a6-fc2c10106f52)

I think it's possible to add a prompt that displays the number of all logs.

```txt
All 1024 items have been filtered out.
```

```txt
There are currently no logs.
```

Other pages, such as recording pages, should also add such prompts to inform users that there is really no content, rather than what error has occurred.

**Comment by F0x1d** [comment]
Added it, you can check it [here](https://github.com/F0x1d/LogFox/actions/runs/6916427825), waiting for UI suggestions

**Comment by F0x1d** [comment]
Done in ee8045753aab7df99b98fc084fa9a972a8a5cfa9
